# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.generic_default_language import GenericDefaultLanguage  # noqa: F401,E501
from swagger_server.models.source import Source  # noqa: F401,E501
from swagger_server.models.time_frame import TimeFrame  # noqa: F401,E501
from swagger_server import util


class Country(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: GenericDefaultLanguage=None, existing: TimeFrame=None, source: Source=None):  # noqa: E501
        """Country - a model defined in Swagger

        :param name: The name of this Country.  # noqa: E501
        :type name: GenericDefaultLanguage
        :param existing: The existing of this Country.  # noqa: E501
        :type existing: TimeFrame
        :param source: The source of this Country.  # noqa: E501
        :type source: Source
        """
        self.swagger_types = {
            'name': GenericDefaultLanguage,
            'existing': TimeFrame,
            'source': Source
        }

        self.attribute_map = {
            'name': 'name',
            'existing': 'existing',
            'source': 'source'
        }
        self._name = name
        self._existing = existing
        self._source = source

    @classmethod
    def from_dict(cls, dikt) -> 'Country':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Country of this Country.  # noqa: E501
        :rtype: Country
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> GenericDefaultLanguage:
        """Gets the name of this Country.


        :return: The name of this Country.
        :rtype: GenericDefaultLanguage
        """
        return self._name

    @name.setter
    def name(self, name: GenericDefaultLanguage):
        """Sets the name of this Country.


        :param name: The name of this Country.
        :type name: GenericDefaultLanguage
        """

        self._name = name

    @property
    def existing(self) -> TimeFrame:
        """Gets the existing of this Country.


        :return: The existing of this Country.
        :rtype: TimeFrame
        """
        return self._existing

    @existing.setter
    def existing(self, existing: TimeFrame):
        """Sets the existing of this Country.


        :param existing: The existing of this Country.
        :type existing: TimeFrame
        """

        self._existing = existing

    @property
    def source(self) -> Source:
        """Gets the source of this Country.


        :return: The source of this Country.
        :rtype: Source
        """
        return self._source

    @source.setter
    def source(self, source: Source):
        """Sets the source of this Country.


        :param source: The source of this Country.
        :type source: Source
        """

        self._source = source
