# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.generic_default_language import GenericDefaultLanguage  # noqa: F401,E501
from swagger_server import util


class GeoPoint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, longitude: float=None, langitude: float=None, name: GenericDefaultLanguage=None):  # noqa: E501
        """GeoPoint - a model defined in Swagger

        :param id: The id of this GeoPoint.  # noqa: E501
        :type id: int
        :param longitude: The longitude of this GeoPoint.  # noqa: E501
        :type longitude: float
        :param langitude: The langitude of this GeoPoint.  # noqa: E501
        :type langitude: float
        :param name: The name of this GeoPoint.  # noqa: E501
        :type name: GenericDefaultLanguage
        """
        self.swagger_types = {
            'id': int,
            'longitude': float,
            'langitude': float,
            'name': GenericDefaultLanguage
        }

        self.attribute_map = {
            'id': 'id',
            'longitude': 'longitude',
            'langitude': 'langitude',
            'name': 'name'
        }
        self._id = id
        self._longitude = longitude
        self._langitude = langitude
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'GeoPoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GeoPoint of this GeoPoint.  # noqa: E501
        :rtype: GeoPoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this GeoPoint.


        :return: The id of this GeoPoint.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this GeoPoint.


        :param id: The id of this GeoPoint.
        :type id: int
        """

        self._id = id

    @property
    def longitude(self) -> float:
        """Gets the longitude of this GeoPoint.


        :return: The longitude of this GeoPoint.
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude: float):
        """Sets the longitude of this GeoPoint.


        :param longitude: The longitude of this GeoPoint.
        :type longitude: float
        """
        if longitude is None:
            raise ValueError("Invalid value for `longitude`, must not be `None`")  # noqa: E501

        self._longitude = longitude

    @property
    def langitude(self) -> float:
        """Gets the langitude of this GeoPoint.


        :return: The langitude of this GeoPoint.
        :rtype: float
        """
        return self._langitude

    @langitude.setter
    def langitude(self, langitude: float):
        """Sets the langitude of this GeoPoint.


        :param langitude: The langitude of this GeoPoint.
        :type langitude: float
        """
        if langitude is None:
            raise ValueError("Invalid value for `langitude`, must not be `None`")  # noqa: E501

        self._langitude = langitude

    @property
    def name(self) -> GenericDefaultLanguage:
        """Gets the name of this GeoPoint.


        :return: The name of this GeoPoint.
        :rtype: GenericDefaultLanguage
        """
        return self._name

    @name.setter
    def name(self, name: GenericDefaultLanguage):
        """Sets the name of this GeoPoint.


        :param name: The name of this GeoPoint.
        :type name: GenericDefaultLanguage
        """

        self._name = name
